### ISSUE TITLE
[Enhancement] Cookbook side nav - Increase color contrast on selected item 

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1314]
**Is your enhancement request related to a problem? Please describe.**

Currently the color contrast between the text color and the background color (both white and medium gray) is not sufficient. I find it difficult to read the text of the selected item.

**Describe the solution you'd like**

I'd like to increase the color contrast between text color and background color of the selected item in the side navigation of the cookbook.

The suggested enhancement below requires very little effort. In `apps/cookbook/src/app/page/side-nav/side-nav.component.scss` a single line has been changed (text color) and another line added (background color):

From:

``` scss
&.is-selected {
  color: get-color('primary');
  font-weight: bold;
}
```

To:

``` scss
&.is-selected {
  color: get-color('primary-contrast');
  background-color: get-color('primary');
  font-weight: bold;
}
```

**Describe alternatives you've considered**

None.

**Additional context**

### Currently

https://user-images.githubusercontent.com/150451/107968533-c2e96380-6fae-11eb-9448-2ff81704fe3a.mov

![before-full-1](https://user-images.githubusercontent.com/150451/107968547-c846ae00-6fae-11eb-975c-cf6483dd44fc.png)

![before-full-2](https://user-images.githubusercontent.com/150451/107969055-7d796600-6faf-11eb-90a5-a5cdaa24ace5.png)

![primary on medium gray](https://user-images.githubusercontent.com/150451/107968642-e6aca980-6fae-11eb-9d0b-5c6c16e3f5c5.png)

![primary on white](https://user-images.githubusercontent.com/150451/107969111-95e98080-6faf-11eb-8f88-77b8671ef2c0.png)

### Suggested enhancement

https://user-images.githubusercontent.com/150451/107968720-ff1cc400-6fae-11eb-9c77-8554e2aeead4.mov

![after-full](https://user-images.githubusercontent.com/150451/107968761-0f34a380-6faf-11eb-97cc-11df36838249.png)

![kirby-black on primary](https://user-images.githubusercontent.com/150451/107968784-1491ee00-6faf-11eb-9095-b65253e521bd.png)
