### ISSUE TITLE
[Housekeeping] Add utility functions for em/rem calculation

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#1785]
- [x] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the housekeeping request

I'd like to add utility functions that calculate `em` and `rem` values given a target size in pixels and a context/base font size.

An example of implementation could be:

```scss
@function em($pixels, $context: font-size('n')) {
  @if unitless($pixels) {
    $pixels: $pixels * 1px;
  }

  @if unitless($context) {
    $context: $context * 1px;
  }

  @return $pixels / $context * 1em;
}

```

and

```scss
@function rem($pixels) {
  @if unitless($pixels) {
    $pixels: $pixels * 1px;
  }

  @return $pixels / font-size('n') * 1rem;
}
```

Usage is e.g.:

```scss
$list-item-font-size: em(16);
```

which would equal `1em` given that the context (base font size) defined by the design token `font-size('n')` is `16px`

## Have you considered any alternatives?

no

## Are there any additional context?

no
