### ISSUE TITLE
Apply customized solutions for non state layer based interactive components (Ionic)

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2150]
- [ ] Ionic components
- [ ] Active state for generic links

**Comment by jkaltoft** [comment]
Suggestion for a starting point for generic link styles for active/pressed state:

``` scss
a:active {
  $gap: utils.size('xxxxs');
  $stroke-width: 1px;

  box-shadow: 0 0 0 $gap #{utils.get-color('background-color')}, 0 0 0 $gap + $stroke-width currentColor;
}
```

- Should be placed within the `link` Sass module `libs/core/src/scss/base/_link.scss`
- Order matters ([:link, :visited, :hover, :active](https://css-tricks.com/snippets/css/link-pseudo-classes-in-order/))
- There's a specificity issue with applying `box-shadow` - perhaps due to applying focus interaction state styles 🤷🏼.
