### ISSUE TITLE
[Research] Github Release Tools

### ISSUE THREAD

**Issue by MadsBuchmann** [kirbydesign/designsystem#2231]
Github has a [release page](https://github.com/kirbydesign/designsystem/releases) for each repository. We should research if it is possible to use the tools provided by Github for our release process. 

Aim of research: "Is it possible to simplify our publish workflows using the tools for releasing Github provides? If we were to rethink our publishing process from scratch today how would we go about setting it up?" 

Additional questions: 
 - Is it possible to streamline the publishing of release candidates of core and designsystem such that i do not have to publish a rc for core and then designsystem, in case i want to test some changes to core?
 - We should streamline how we release core and designsystem; the first uses 'npm publish' while the latter uses 'npm run publish'.

**Comment by RasmusKjeldgaard** [comment]
## Release workflow proposal
### Github Release Notes
We would like to generate Release Notes semi-automatically. For this, I suggest we tag our PR’s with either `ignore-for-release`
 `breaking-change` `feature` or `fix` labels. This tagging can be automated over time if we want. 

With the following template we have a startingpoint when using Github Releases, where we should not have to change much in the release notes prior to releasing - given that our PR’s are nicely named (see next point). 

```yaml
# .github/release.yml
changelog:
  exclude:
    labels:
    	- ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
		  - fix
        - "*"
```

### Pull Requests
Prior to merging each pull request, it should be squashed into one commit with a descriptive title (the PR title). Otherwise it will be very hard to generate meaningful release notes. 

*Optional:*
[Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) - if we want to automate version bumps down the line we should consider to establish commit-conventions that follows the above system with feature/fix and breaking changes. 

### Versioning
Versioning can be done by hand initially, by determining the nature of the changes, and bumping the version accordingly, prior to creating the Release Notes. The version tag (possibly created during publish step) should be pushed. 

### Publishing 
I suggest we start by manually using the publish-script, and then start working on restructuring the repo a bit, to isolate each package and app into its own sub-project. 

Consider [Lerna](https://lerna.js.org/) here. 

### Only merge to one branch
If we consider our packages to be the version running in production, and we publish our packages from what is now the develop branch, we don’t really need an additional branch to publish from.
