### ISSUE TITLE
[Housekeeping] Automate release notes and publish

### ISSUE THREAD

**Issue by RasmusKjeldgaard** [kirbydesign/designsystem#2466]
Should be added to our github config under `.github/release.yml`. 

Could look something like: 
``` yml
# .github/release.yml
changelog:
  exclude:
    labels:
    	- ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - fix
        - "*"
```
See background here: https://github.com/kirbydesign/designsystem/issues/2231#issuecomment-1229916291
And github release notes docs here: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
